### ISSUE TITLE
Blank output in all example scenes

### ISSUE THREAD

**Issue by mmmovania** [huisedenanhai/simple-volume#1]
I managed to compile and run your code on a windows 8.1 64bit machine on VStudio2019 but I get a black output image for all example scenes.  I get a few warning messages on console about some temporary file not being delete able when the openvdb file is parsed. What could be causing this issue? Any idea?

**Comment by mmmovania** [comment]
I guess you are not doing any error handling adding that in i get an error at the time of call of kernel saying
`CUDA Error: invalid device function`
This is after the launch2d call returns. By the way I have NVIDIA GeForce TitanXp hardware.

**Comment by mmmovania** [comment]
I am on CUDA 10.2. I guess it could be due to using the old CUDA version. Let me try on CUDA 11 in Win10 to see if it work.

**Comment by huisedenanhai** [comment]
The crash might be caused by the fixed cuda architecture number setting in line 3 of CMakeLists.txt. Which is

```
set(CMAKE_CUDA_ARCHITECTURES 75)
```

75 stands for Turing architecture, which includes my RTX 2060 card.

Your card Titan Xp uses Pascal architecture, with arch code 61.

You can look up for arch code of other cards [here](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/).

You can replace the line with

```
set(CMAKE_CUDA_ARCHITECTURES 61)
```

and see if that works. I have no pascal card to test that.

**Comment by mmmovania** [comment]
Thanks but it still does not work I do not get any error but my driver crashes mid way during kernel launch. The output is still black.

**Comment by huisedenanhai** [comment]
I found there is another hard-coded arch number in CMakeLists.txt at line 22:

```
set_property(TARGET volume PROPERTY CUDA_ARCHITECTURES 75)
```

Have you tried to replace it with correct arch number?

**Comment by huisedenanhai** [comment]
I know what's going on. The line `set_property(TARGET volume PROPERTY CUDA_ARCHITECTURES 75)` overrides the global `CMAKE_CUDA_ARCHITECTURES` configuration. By increment the cuda arch number, I can reproduce the kernel crash and black output, just as you described.

I pushed a fix 31bf38affcc56be83c9c983f99d178c0e71f7617 by including more arch in the CMake compile configuration. You can update the code and see if that works.

**Comment by mmmovania** [comment]
I already tried that but I get the following CUDA kernel timeout error. My console window displays the following. 
```
J:/Github/simple-volume/data
load config ../data/bunny_cloud_dt.toml
WARNING: WARNING: file file WARNING: C:\Users\CUDA1\AppData\Local\Temp\s41w.0C:\
Users\CUDA1\AppData\Local\Temp\s41w.0 might have changed on disk might have chan
ged on disk since it was opened since it was opened

file C:\Users\CUDA1\AppData\Local\Temp\s41w.0 might have changed on disk since i
t was opened
WARNING: WARNING: WARNING: file file C:\Users\CUDA1\AppData\Local\Temp\s41w.0C:\
Users\CUDA1\AppData\Local\Temp\s41w.0 might have changed on diskfile  might have
 changed on disk since it was opened since it was opened

C:\Users\CUDA1\AppData\Local\Temp\s41w.0 might have changed on disk since it was
 opened
WARNING: WARNING: file file C:\Users\CUDA1\AppData\Local\Temp\s41w.0C:\Users\CUD
A1\AppData\Local\Temp\s41w.0 might have changed on disk might have changed on di
sk since it was opened since it was opened

WARNING: failed to remove temporary file C:\Users\CUDA1\AppData\Local\Temp\s41w.
0 (permission denied)
load success
min: 0.000000, max: 2.792298
render start at Sun Jan  2 19:53:24 2022
render
width 800, height 600
render finished at Sun Jan  2 19:53:26 2022
duration 0:0:2.20065
result written to "bunny_cloud_dt"
CUDA Runtime Error: the launch timed out and was terminated J:\Github\simple-vol
ume\third_party\nanovdb\include\nanovdb/util/CudaDeviceBuffer.h 191

J:\Github\simple-volume\build\Debug\volume.exe (process 5252) exited with code 7
02.
Press any key to close this window . . .
```

**Comment by huisedenanhai** [comment]
It seems the program launches and runs for a while. The termination may be caused by your system configuration. The operating system will terminate your program on the main display GPU if it runs for too long, just to keep the UI interactive. 

The solution is system dependent. You can choose a seperate card with no active display for computation task, or adjust the system configuration (like increase watchdog timer).

**Comment by mmmovania** [comment]
Yeah but I am surprised at why the computations dont converge within the alotted time. I can run a my own CUDA based volume path tracer code with multiple bounces of light using delta, ratio, residual ratio and spectral MIS code easily without a problem.

**Comment by huisedenanhai** [comment]
I don't know. I personally haven't run into the time-out issue with CUDA. One of my friends did meet that problem when working on his Optix renderer but the machine he used at that time was of low spec and quite old.

I guess the kernel occupies GPU for too long because I only launch it once and wait for the computation to finish. Launch multiple times and accumulate the result might alleviate the issue but I don't have device to test that.

By the way, how did you solve the precision issue of spectral MIS when hit count and density ratio of different color components are high? In my experiment one path may contain thousands of hits (either null or real), any small density ratio for different components results in very high pdf difference. I tried to use russian roulette to reduce the hit count but it does not really helps. (Code for spectral MIS in the repo is rotted. I will rewrite it if I have time.)

**Comment by mmmovania** [comment]
My spectralMIS implementation was basically not that sophisticated so I never faced this high pdf differences that you are talking about. But for the delta, ratio and residual ratio implementations, the paths converged for the scenes i used. Anyways thanks for your inputs anyways. I am closing this issue for now.
